export class UserExistsError extends Error {}
export class UserNotFoundError extends Error {}
export class UserIsAlreadyBlockedError extends Error {}
export class UserIsAlreadyUnblockedError extends Error {}
export class ForgotPasswordDadosInvalidoError extends Error {}
export class CognitoException extends Error {}
export class UserGroupNotFoundError extends Error {}
export class UserNotPermittedError extends Error {}
export class NonRepresentativeUserCannotSign extends Error {}
export class WrongBlockReasonError extends Error {}
export class InvalidParameterError extends Error {}
export class ResourceNotFoundException extends Error {}
export class MissingRequiredParameter extends Error {}
export class InvalidParameterException extends Error {}
export class NotAuthorizedException extends Error {}
export class InvalidLoginData extends Error {}
export class ChangePasswordException extends Error {}
export class AccessTokenException extends Error {}
